### PR TITLE
SAGE-1372: Split waggle-edge-stack repo to only contain the minimal node configs

### PR DESCRIPTION
**Pull request by iperezx**
- Copies over the virtual node ansible scripts from https://github.com/waggle-sensor/waggle-edge-stack
- Modifies the Dockerfile for passing in VSN and node id at build time
- Add github workflows to build and push to Dockerhub. Currently I am pushing to my account: https://hub.docker.com/repository/docker/iperezx/node-platforms and needs some modifcations to change to the waggle Dockerhub account (see this issue: https://github.com/waggle-sensor/.github/issues/1)

### CODE REVIEW

**Comment by seanshahkarami** [comment]
If I understand right, the main "dev" intent here is to extract (and eventually remove) the Vagrant / VM + Ansible stuff from the WES repo into a standalone deployment in this repo?

**Comment by iperezx** [comment]
Yes. @jswantek wants to separate it from https://github.com/waggle-sensor/waggle-edge-stack and refactor it. This PR is only the copy over and not the refactoring part.

**Comment by iperezx** [comment]
Can I get write access?

If not can you merge this pull request? @jswantek @seanshahkarami 

Before merging the PR, can you guys also create an action secret called DOCKER_ORG with the value `waggle`. The workflows will fail on merge if DOCKER_ORG is not set.

**Comment by jswantek** [comment]
done. you have write access.

i added an organization secrete `DOCKER_ORG` to `waggle`

**Pull request merged**
